apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nexus-{{ .Release.Namespace }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.nexus.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.nexus.serviceAccountName }}-{{ .Release.Namespace }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
