apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
    {{- include "nexus-operator.metaLabels" . | nindent 4 }}
  name: artifactory
spec:
  ports:
    - name: artifactory
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: nexus
  sessionAffinity: None
  type: ClusterIP
