apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakRealmRoleBatch
metadata:
  name: nexus
spec:
  realm: {{ .Values.keycloakIntegration.realm }}
  roles:
  {{- range .Values.keycloakIntegration.roles }}
    - attributes: null
      composite: false
      composites: null
      description: {{ . }}
      name: {{ . }}
  {{- end }}