name: keycloak-operator
image:
  name: epamedp/keycloak-operator
  version: 1.8.0-SNAPSHOT.12
resources:
  limits:
    cpu: 200m
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

keycloak:
  url: https://keycloak-keycloak.apps.uat.mdtu-ddm.projects.epam.com
