kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: nexuses.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    plural: nexuses
    singular: nexus
    kind: Nexus
    listKind: NexusList
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: >-
                APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the
                latest internal value, and may reject unrecognized values. More
                info:
                https://git.k8s.io/community/contributors/devel/scripts-conventions.md#resources
              type: string
            kind:
              description: >-
                Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the
                client submits requests to. Cannot be updated. In CamelCase.
                More info:
                https://git.k8s.io/community/contributors/devel/scripts-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - image
                - version
                - keycloakSpec
                - volumes
              properties:
                basePath:
                  type: string
                image:
                  type: string
                keycloakSpec:
                  type: object
                  required:
                    - enabled
                  properties:
                    enabled:
                      type: boolean
                    realm:
                      type: string
                    roles:
                      type: array
                users:
                  type: array
                version:
                  type: string
                volumes:
                  type: array
            status:
              type: object
      subresources:
        status: {}
  conversion:
    strategy: None
